settings:
  # Persists the player's pvp state, so they don't have to set it every time they join
  persist-pvp-state: true
  # If true, PvP will be enabled by default, If false it will be turned off by default
  default-pvp-state: false
  # Cooldown in seconds for the /pvp command
  cooldown: 0
  # Worlds to disable PvP in
  blocked-worlds: [ ]

messages:
  # Help
  help-header: '&a&lCommands:'
  help-general-usage: '&aUse /pvp <toggle|on|off|status> to change/view pvp state.'
  help-view-others: '&aUse /pvp <player> to see another players pvp state.'
  help-set-others: '&aUse /pvp <player> <on|off> to set another players pvp state.'
  no-player: '&cCould not find a player with the name %s'
  # -- PVP
  pvp-state-enabled: '&aPvP is now &a&lENABLED&a.'
  pvp-state-disabled: '&aPvP is now &c&lDISABLED&a.'
  pvp-state-already-enabled: '&cPvP is already &a&lENABLED&a.'
  pvp-state-already-disabled: '&cPvP is already &c&lDISABLED&a.'
  pvp-state-change-others: '&aYou have changed %s''s PvP state to %s.'
  pvp-cooldown: '&cYou must wait %s seconds before changing your PvP state again.'
  # -- State
  pvp-enabled: '&cYou have pvp enabled!'
  pvp-disabled: '&cYou have pvp disabled!'
  pvp-disabled-others: '&c%s has pvp disabled!'
  # -- PVP World
  pvp-world-change-disabled: '&aYour pvp has been disabled because the world you entered does not allow pvp.'
  pvp-world-change-enabled: '&aYour pvp has been enabled because the world you enter requires pvp.'
  pvp-world-cannot-change-self: '&cYou cannot change pvp state in this world.'
  pvp-world-cannot-change-others: '&cYou cannot change pvp state in that world.'



