name: PvPToggle
main: cc.ricecx.pvptoggle.PvPToggle
author: RiceCX
website: https://ricecx.cc
version: 1.0.0
api-version: 1.13
permissions:
  "pvptoggle.bypass":
    description: "Allows you to bypass the cooldown"
    default: false